### PR TITLE
Fix cron timeout

### LINKED ISSUE #8: Cron worker runs multiple times during one second
Cron worker runs multiple times during one second with every minute expression.

The following piece of code demonstrates the issue:
```javascript
const Bossbat = require('bossbat');
const bossbat = new Bossbat();
let i = 0;

bossbat.hire('work', {
  cron: '*/1 * * * *',
  work: () => {
    console.log('Working...', new Date().toString(), i);
    i++;
  }
});
```
**Output:**
```
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 0
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 1
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 2
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 3
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 4
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 5
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 6
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 7
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 8
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 9
Working... Sun Feb 26 2017 14:30:01 GMT+0200 (EET) 10
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 11
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 12
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 13
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 14
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 15
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 16
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 17
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 18
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 19
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 20
Working... Sun Feb 26 2017 14:31:01 GMT+0200 (EET) 21
```
**Expected output:**
```
Working... Sun Feb 26 2017 14:30:00 GMT+0200 (EET) 0
Working... Sun Feb 26 2017 14:31:00 GMT+0200 (EET) 1
```

The issue occurs only if the runner completes relatively fast (in a couple of milliseconds).

### PR DESCRIPTION
**Pull request by tjokimie**
Closes #8.

If `cronTimeout` is `0` or negative, the runner has already been invoked. Instead of setting `cronTimeout` to `1` (one millisecond) we should get the next time from the iterator.

### CODE REVIEW

**Comment by tjokimie** [comment]
I did not write a test case for this one as I couldn't reproduce the issue with every second cron expression. If I would write a test with the every minute expression it would slow down the tests significantly 😞

File: src/Bossbat.js [hunk 1]
```diff
@@ -127,10 +127,9 @@ export default class Bossbat {
         throw new Error(`Unknown interval of type "${typeOfEvery}" passed to hire.`);
       }
     } else if (definition.cron) {
-      const nextTime = parseExpression(definition.cron, { iterator: false }).next().getTime();
-      const cronTimeout = nextTime - Date.now();
-      // Force timeout to be at least 1:
-      timeout = cronTimeout >= 1 ? cronTimeout : 1;
+      const iterator = parseExpression(definition.cron, { iterator: false });
+      const cronTimeout = iterator.next().getTime() - Date.now();
+      timeout = cronTimeout > 0 ? cronTimeout : iterator.next().getTime() - Date.now();
```
Comment (kesne) [inline src/Bossbat.js]: Instead of replicating the same iterator code twice, could we just wrap this into a function we can call?

**Comment by kesne** [comment]
This is great, thanks for fixing this bug. I'm curious when the time returned from the iterator would be negative. 0 seems possible although unlikely.

**Comment by tjokimie** [comment]
The time returned from the iterator is not be negative, but `cronTimeout` (the result of `iterator.next().getTime() - Date.now()`) can be negative as `iterator.next().getTime()` can return current time and after that `Date.now()` will be subtracted from it.

File: src/Bossbat.js (hunk 1 above)
Comment (tjokimie) [inline src/Bossbat.js]: :+1: Extracted `nextCronTimeout`.

**Comment by kesne** [comment]
Ah fair, I confirmed that this can happen in my console too:

```js
for (var i = 0; i < 10000; i++) console.log(Date.now() - Date.now())
```

This sometimes prints negative numbers.

**Comment by kesne** [comment]
Published as `bossbat@1.1.1`.
